import { jsPDF } from "jspdf";
import { CreativeBrief } from "../lib/firebase";

export const generateBriefPDF = (brief: CreativeBrief, brandName?: string): jsPDF => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  // Color Palette - Slate & Deep violet theme
  const primaryColor = [15, 23, 42]; // Slate-900
  const accentColor = [124, 58, 237]; // Violet-600
  const textColor = [51, 65, 85]; // Slate-700
  const darkTextColor = [15, 23, 42]; // Slate-900

  // Draw header card banner
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 42, "F");

  // Accent Line under header
  doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.rect(0, 42, 210, 2, "F");

  // Title in Banner
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("CREATIVE CAMPAIGN BRIEF", 20, 18);

  // Subtitle/Metadata in Banner
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(167, 139, 250); // Light violet-400
  const brandLabel = brandName ? `BRAND: ${brandName.toUpperCase()}` : "CREATIVE CAMPAIGN";
  doc.text(`${brandLabel}  |  STATUS: ${brief.status.toUpperCase()}  |  ID: ${brief.id.substring(0, 8).toUpperCase()}`, 20, 26);

  // Decorative border
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.setLineWidth(0.5);
  doc.line(20, 52, 190, 52);

  // Brief Title Section
  let currentY = 58;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  doc.text(brief.title, 20, currentY);
  currentY += 10;

  const drawSection = (title: string, content: string) => {
    // If we're getting close to the page bottom, we can add a page, but our briefs are short and easily fit.
    if (currentY > 250) {
      doc.addPage();
      currentY = 20;
    }

    // Section Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.text(title.toUpperCase(), 20, currentY);
    currentY += 3;

    // Underline
    doc.setDrawColor(241, 245, 249); // Slate-100
    doc.setLineWidth(0.5);
    doc.line(20, currentY, 190, currentY);
    currentY += 6;

    // Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);

    // Word Wrap Content
    const splitContent = doc.splitTextToSize(content || "N/A", 170);
    doc.text(splitContent, 20, currentY);
    currentY += (splitContent.length * 5.2) + 8;
  };

  drawSection("Campaign Objective", brief.objective);
  drawSection("Target Audience", brief.targetAudience);
  drawSection("Core Positioning Copy / Key Message", `"${brief.keyMessage}"`);
  drawSection("Deliverables & Scope", brief.deliverables);

  // Footer
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(20, 275, 190, 275);
  
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // Slate-400
  doc.text("Generated by Creative Briefs Desk via Google AI Studio", 20, 282);
  
  const today = new Date().toLocaleDateString();
  doc.text(`Date: ${today}`, 190, 282, { align: "right" });

  return doc;
};
